# Generated by Django 4.1.4 on 2022-12-17 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dining_room_service', '0003_alter_menu_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diningroom',
            name='timetable',
        ),
        migrations.AddField(
            model_name='menu',
            name='isExtended',
            field=models.BooleanField(default=True, verbose_name='Расширенное меню или нет'),
        ),
        migrations.AlterField(
            model_name='diningroom',
            name='status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSE', 'CLOSE')], default='OPEN', max_length=100),
        ),
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('STUDENT', 'STUDENT'), ('TEACHER', 'TEACHER'), ('COOK', 'COOK'), ('ADMIN', 'ADMIN')], default='STUDENT', max_length=100),
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayOfWeek', models.IntegerField(verbose_name='День недели')),
                ('fromTime', models.TimeField(verbose_name='Начало')),
                ('toTime', models.TimeField(verbose_name='Закрытие')),
                ('diningRoomId', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dining_room_service.diningroom')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
    ]
