# Generated by Django 4.1.4 on 2022-12-17 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dining_room_service', '0004_remove_diningroom_timetable_menu_isextended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='diningRoomId',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dining_room_service.diningroom', verbose_name='Столовая'),
        ),
    ]
