# Generated by Django 4.1.4 on 2022-12-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining_room_service', '0005_alter_timetable_diningroomid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='dayOfWeek',
            field=models.CharField(choices=[('MONDAY', 'MONDAY'), ('TUESDAY', 'TUESDAY'), ('WEDNESDAY', 'WEDNESDAY'), ('THURSDAY', 'THURSDAY'), ('FRIDAY', 'FRIDAY'), ('SATURDAY', 'SATURDAY'), ('SUNDAY', 'SUNDAY')], default='MONDAY', max_length=100),
        ),
    ]
