# Generated by Django 4.1.4 on 2022-12-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining_room_service', '0006_alter_timetable_dayofweek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diningroom',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
    ]
