# Generated by Django 4.1.4 on 2022-12-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dining_room_service', '0007_alter_diningroom_name_alter_dish_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='name',
            field=models.CharField(default='Меню', max_length=100, verbose_name='Название'),
        ),
    ]
