# Generated by Django 4.1.4 on 2022-12-17 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dining_room_service', '0008_menu_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='name',
        ),
    ]
